apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenisapp
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: tenisapp
  template:
    metadata:
      labels:
        app: sample-app
        service: tenisapp
    spec:
      containers:
        - name: tenisapp
          image: teniscontainer.azurecr.io/tenisapp:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: WebApiBaseAddress
              value: http://localhost/swagger