apiVersion: v1
kind: Service
metadata:
  name: tenisapp
  labels:
    app: sample-app
    service: tenisapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: tenisapp