name: Build and deploy API to Azure Web Service
on: push
env:
  AZURE_WEB_PACKAGE_PATH: .
  AZURE_WEBAPP_NAME: tenisapp
jobs:
  BuildAndDeploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x
          
      - name: Restore
        run: dotnet restore
          
      - name: Build API
        run: dotnet build TenisApp.Api/TenisApp.Api.csproj -c Release
        
      - name: Install EF Tool
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef
            
      - name: Create Database migration script
        run: dotnet ef migrations script -s TenisApp.Api/TenisApp.Api.csproj -p TenisApp.DataAccess/TenisApp.DataAccess.csproj -o ${{env.DOTNET_ROOT}}/sql/sql-script.sql -i
        
      - name: Azure login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.1
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
          path: ${{env.DOTNET_ROOT}}/sql/sql-script.sql
          
      - name: Publish API
        run: dotnet publish TenisApp.Api/TenisApp.Api.csproj -c Release -o '${{ env.AZURE_WEB_PACKAGE_PATH }}/myapp'
        
      - name: Azure WebApp deploy
        uses: Azure/webapps-deploy@v2.2.6
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: development
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
          package: '${{ env.AZURE_WEB_PACKAGE_PATH }}/myapp'
          
      
          
      
