name: Build and deploy API to Azure Web Service
on: push
env:
  AZURE_WEB_PACKAGE_PATH: .
  AZURE_WEBAPP_NAME: tenisapp
jobs:
  BuildAndDeploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure App Service Settings
        uses: Azure/appservice-settings@v1 
        with:
          app-name: tenisapp
          slot-name: 'development'
          connection-string-json: '{ "MainDatabase": "${{ secrets.AZURE_SQL_CONNECTIONSTRING }}" }'
          
      - name: fail step
        run: |
          return 1;
          
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x
          
      - name: Restore
        run: dotnet restore
          
      - name: Build API
        run: dotnet build TenisApp.Api/TenisApp.Api.csproj -c Release
        
      - name: Install EF Tool
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef
            
      - name: Create Database migration script
        run: dotnet ef migrations script -s TenisApp.Api/TenisApp.Api.csproj -p TenisApp.DataAccess/TenisApp.DataAccess.csproj -o ${{env.DOTNET_ROOT}}/sql/sql-script.sql -i
        
      - name: upload sql script
        uses: actions/upload-artifact@v3.1.2
        with:
          name: SQL migration script
          path: ${{env.DOTNET_ROOT}}/sql/sql-script.sql
        
      - name: Azure login
        uses: Azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2.1
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
          path: ${{env.DOTNET_ROOT}}/sql/sql-script.sql
          
      - name: Publish API
        if: ${{ 1 == 0 }}
        run: dotnet publish TenisApp.Api/TenisApp.Api.csproj -c Release -o '${{ env.AZURE_WEB_PACKAGE_PATH }}/myapp'
        
      - name: Azure WebApp deploy
        if: ${{ 1 == 0 }}
        uses: Azure/webapps-deploy@v2.2.6
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: development
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
          package: '${{ env.AZURE_WEB_PACKAGE_PATH }}/myapp'

          
      
          
      
