name: Deploy app to Azure Container Registry
on:
  workflow_dispatch:

env:
  AZURE_LOGON: ${{ secrets.ACR_NAME }}.azurecr.io
  IMG_NAME: ${{ secrets.ACR_NAME }}.azurecr.io/tenisapp:${{ github.sha }}
  WORK_DIR: ./deploy

jobs:
  ContainerDeployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_LOGON }}
          username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
       
      - run: docker build . -f ${{ env.WORK_DIR }}/Dockerfile -t ${{ env.IMG_NAME }}
      - run: docker push ${{ env.IMG_NAME }}

  AKSDeployment:
    runs-on: ubuntu-latest
    needs: ContainerDeployment
    if: github.ref == 'refs/heads/master'
    #env:
      #NAMESPACE: tenis

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CONTAINER_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_NAME }}
      
      - uses: azure/k8s-create-secret@v4
        with:
              secret-name: ${{ secrets.AKS_SECRET }}
              container-registry-url: ${{ env.AZURE_LOGON }}
              container-registry-username: ${{ secrets.SERVICE_PRINCIPAL_ID }}
              container-registry-password: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      - uses: Azure/k8s-deploy@v4
        with:
          manifests: |
              manifests/deployment.yml
              manifests/service.yml
          images: |
            ${{ env.IMG_NAME }}
          imagepullsecrets: |
              ${{ secrets.AKS_SECRET }}
      
      
      
