name: Build check on PR
on:
  pull_request:
    types: [opened, reopened]
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: Manual trigger
jobs:
  PR-check:
    name: Build solution and execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "we are on branch ${{ github.ref }} of repository ${{ github.repostiory }}"
      - run: echo "executing on system ${{ runner.os }} github runner"
      - name: Setup .NET
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x
      - run: ls ${{ github.workspace }}
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --logger trx --result-directory TestResults
      - uses: actions/upload-artifact@v3.1.2
        if: ${{ always() }}
        with:
          path: TestResults
          name: test-results
