name: Build check on PR
on:
  pull_request:
    types: [opened, reopened]
    branches: [ master ]
  workflow_dispatch:
    inputs:
      tags:
        description: Manual trigger
jobs:
  PR-check:
    name: Build solution and execute tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "we are on branch ${{ github.ref }} of repository ${{ github.repostiory }}"
      - run: echo "executing on system ${{ runner.os }}"
